name: pixpdv_sdk
description: Package para integração com o PixPDV
version: 0.0.1
homepage: https://pixpdv.com.br/

environment:

  # Versão do Dart 
  # suportada de 2.19.0 até 3.0.0
  sdk: '>=2.19.0 <3.0.0'

  # Versão do Flutter 
  # suportada de 1.17.0 até 2.0.0
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  intl: ">=0.18.0 <0.19.0"
  crypto: ">=3.0.2 <4.0.0"
  dio: ">=5.0.1 <6.0.0"
  retrofit: ">=4.0.1 <5.0.0"
  json_annotation: ">=4.8.0 <5.0.0"
  json_serializable: ">=6.6.1 <7.0.0"

dev_dependencies:

  flutter_lints: ">=2.0.0 <3.0.0"

  flutter_test:
    sdk: flutter

  build_runner: ">=2.3.3 <3.0.0"
  retrofit_generator: ">=5.0.0 <6.0.0"

flutter:
